--[[
    DOORway default Hyprland settings.

    Originally `defaults.conf` (hyprlang). Hyprland 0.55+ lua migration.

    Covers monitor fallback, decoration, animations, input, layouts, misc,
    xwayland, and floating-window snap. Theme-driven values live in
    dynamic.lua; this file is intentionally static.
--]]

-- // █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
-- // █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

-- Fallback monitor: any output, preferred mode, auto-positioned.
-- See https://wiki.hypr.land/Configuring/Monitors/
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

-- // █▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░
-- // ▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄

hl.config({
    decoration = {
        rounding           = 10,
        dim_special        = 0.3,
        -- active_opacity and inactive_opacity live in userprefs.lua (loads first)
        -- so they can be driven by doorway.input without being overridden here.
        fullscreen_opacity = 1,
        shadow = {
            enabled = false,
        },
        blur = {
            enabled           = true,
            size              = 6,
            passes            = 3,
            new_optimizations = true,
            ignore_opacity    = true,
            xray              = false,
            special           = true,
        },
    },

    -- // ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
    -- // █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
    -- Only `animations.enabled` is a valid HL.ConfigKey; bezier curves and
    -- per-leaf animation specs use hl.curve / hl.animation below.
    animations = {
        enabled = true,
    },

    -- // █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
    -- // █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█
    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    -- // █▀▄▀█ █ █▀ █▀▀
    -- // █░▀░█ █ ▄█ █▄▄
    misc = {
        vrr                       = 0,
        disable_hyprland_logo     = true,
        disable_splash_rendering  = true,
        force_default_wallpaper   = 0,
        anr_missed_pings          = 5,
        allow_session_lock_restore = true,
    },

    xwayland = {
        force_zero_scaling = true,
    },

    general = {
        gaps_in          = 3,
        gaps_out         = 8,
        border_size      = 2,
        layout           = "dwindle",
        resize_on_border = true,
        snap = {
            enabled = true,
        },
    },
})

-- // █▀▀ █░█ █▀█ █░█ █▀▀ █▀
-- // █▄▄ █▄█ █▀▄ ▀▄▀ ██▄ ▄█
-- Bezier curves: hyprlang `bezier = name, x0, y0, x1, y1` becomes
-- hl.curve(name, {type="bezier", points={{x0,y0},{x1,y1}}}). See the
-- vendored example at /nix/store/.../hyprland-0.55.2/share/hypr/hyprland.lua.
hl.curve("wind",   { type = "bezier", points = { {0.05, 0.9 }, {0.1, 1.05} } })
hl.curve("winIn",  { type = "bezier", points = { {0.1,  1.1 }, {0.1, 1.1 } } })
hl.curve("winOut", { type = "bezier", points = { {0.3, -0.3 }, {0,   1   } } })
hl.curve("liner",  { type = "bezier", points = { {1,    1   }, {1,   1   } } })

-- Animations: hyprlang `animation = leaf, on, speed, curve, [style]` becomes
-- hl.animation({leaf=..., enabled=..., speed=..., bezier=..., style=...}).
hl.animation({ leaf = "windows",     enabled = true, speed = 6,  bezier = "wind",    style = "slide" })
hl.animation({ leaf = "windowsIn",   enabled = true, speed = 6,  bezier = "winIn",   style = "slide" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 5,  bezier = "winOut",  style = "slide" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 5,  bezier = "wind",    style = "slide" })
hl.animation({ leaf = "border",      enabled = true, speed = 1,  bezier = "liner"                    })
hl.animation({ leaf = "borderangle", enabled = true, speed = 30, bezier = "liner",   style = "once"  })
hl.animation({ leaf = "fade",        enabled = true, speed = 10, bezier = "default"                  })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 5,  bezier = "wind"                     })

-- Touchpad gestures. See https://wiki.hypr.land/Configuring/Gestures/
-- Guard: hl.gesture is a Lua-specific binding function; existence check follows the
-- same pattern as hl.source in dynamic.lua — avoids a crash if not yet implemented.
if hl.gesture then
    hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
    hl.gesture({ fingers = 3, direction = "pinchin",    action = "float", action_modifier = "tile" })
    hl.gesture({ fingers = 3, direction = "pinchout",   action = "float", action_modifier = "float" })
end

-- Optional theme override generated by Home Manager into ~/.config/hypr/.
-- Falls back silently to the static values above for non-Nix installs.
local _t_ok, _t = pcall(require, "doorway-theme")
if _t_ok then
    hl.config({
        general = {
            gaps_in     = _t.gaps_in,
            gaps_out    = _t.gaps_out,
            border_size = _t.border_size,
            layout      = _t.layout,
        },
        decoration = {
            rounding = _t.rounding,
            blur = {
                enabled = _t.blur_enabled,
                size    = _t.blur_size,
                passes  = _t.blur_passes,
            },
        },
    })
end
