--[[
    DOORway shared variable module.

    All Phase 6 core files (dynamic, startup, finale) that need shared state
    do `local vars = require("variables")` to access these values.

    lua's require() caches modules, so requiring this from multiple files
    returns the same table — no re-evaluation.

    Originally `variables.conf` (hyprlang). Hyprland 0.55+ lua migration.
--]]

-- Optional cursor override generated by Home Manager into ~/.config/hypr/.
-- Falls back silently to defaults for non-Nix installs or before first rebuild.
local _c_ok, _c = pcall(require, "doorway-cursor")

-- Optional font override generated by Home Manager into ~/.config/hypr/.
local _f_ok, _f = pcall(require, "doorway-fonts")

local M = {
    -- Modifier
    mainMod = "SUPER",
    MOD     = "SUPER",

    -- App commands (mirror hyprlang $VAR names so keybindings.lua can read them)
    QUICKAPPS  = "",
    BROWSER    = "doorway-shell open --fall firefox web-browser",
    EDITOR     = "doorway-shell open --fall code-oss text-editor",
    EXPLORER   = "doorway-shell open --fall dolphin file-manager",
    TERMINAL   = "doorway-shell app -T",
    LOCKSCREEN = "hyprlock",
    KILLACTIVE = 'hyprctl dispatch killactive ""',

    -- GTK / colour scheme
    GTK_THEME     = "Wallbash-Gtk",
    ICON_THEME    = "Tela-dracula",
    COLOR_SCHEME  = "prefer-dark",
    BUTTON_LAYOUT = "",

    -- Cursor (defaults overridden by ~/.config/hypr/doorway-cursor.lua when present)
    CURSOR_THEME = _c_ok and _c.name or "oreo_spark_pink_cursors",
    CURSOR_SIZE  = _c_ok and _c.size or 24,

    -- Fonts (defaults overridden by ~/.config/hypr/doorway-fonts.lua when present)
    FONT                = _f_ok and _f.ui_name   or "Cantarell",
    FONT_SIZE           = _f_ok and _f.ui_size   or 10,
    DOCUMENT_FONT       = _f_ok and _f.ui_name   or "Cantarell",
    DOCUMENT_FONT_SIZE  = _f_ok and _f.ui_size   or 10,
    MONOSPACE_FONT      = _f_ok and _f.mono_name or "CaskaydiaCove Nerd Font Mono",
    MONOSPACE_FONT_SIZE = _f_ok and _f.mono_size or 9,
    NOTIFICATION_FONT   = "Mononoki Nerd Font Mono",
    BAR_FONT            = _f_ok and _f.interface or "JetBrainsMono Nerd Font",
    MENU_FONT           = _f_ok and _f.interface or "JetBrainsMono Nerd Font",
    GROUPBAR_FONT       = _f_ok and _f.interface or "JetBrainsMono Nerd Font",
    FONT_ANTIALIASING   = "rgba",
    FONT_HINTING        = "",

    -- Extras
    CODE_THEME = "",
    SDDM_THEME = "",

    -- Note: the historical `start` table (per-service exec strings for the HyDE-era
    -- launch-unit.sh + app() pattern) was removed in Pass 7+ once every entry was
    -- migrated to declarative systemd.user.services in flake.nix (Passes 2-6.5) or
    -- to system-level NixOS modules (gnome-keyring → services.gnome.gnome-keyring
    -- in HALLway). See TODO.md Phase 9 for the migration history.
}

return M
