import qs.modules.common
import QtQuick
import Quickshell

/**
 * A matte, printed magazine-page surface — the left sidebar's identity, deliberately
 * opposite the walnut shell (it's "the open magazine on the desk"). Warm uncoated cream
 * with a faint fibre grain and a soft top-light (no glare), bound at the LEFT spine and
 * lifting off the desk along its BOTTOM + RIGHT outer edges (a stack of page fore-edges
 * with a cast lift shadow, curling at the bottom-right corner). Always light — a printed
 * page does not follow dark mode.
 */
Item {
    id: root
    property real radius: 0
    property bool topLight: true   // soft matte overhead light (replaces the old gloss sweep)
    property bool grain: true      // fibre texture
    property bool spine: true      // left-edge binding gutter
    property bool lift: true       // bottom + right page-edge lift
    property int liftSize: 22      // depth of the page-edge stack
    property int spineWidth: 26    // reach of the gutter shadow

    // Uncoated-stock palette.
    readonly property color paperTop:    "#F7F1E5"
    readonly property color paperBottom: "#ECE2CC"
    readonly property color paperEdge:   "#D6C6A2"
    readonly property color pageLight:   "#FCF7ED"
    readonly property color pageMid:     "#DFD0AE"
    readonly property color pageShadow:  "#B39F73"

    // Paper body (clipped so grain, top-light, spine and lift stay inside the rounded page).
    Rectangle {
        id: page
        anchors.fill: parent
        radius: root.radius
        clip: true
        gradient: Gradient {
            GradientStop { position: 0.0; color: root.paperTop }
            GradientStop { position: 1.0; color: root.paperBottom }
        }

        // Fibre grain — a seamlessly-tiling low-contrast noise texture (committed PNG,
        // generated by assets/textures/gen-paper.sh; the read-only Nix store can't make it
        // at runtime). Same load pattern as WalnutBackground's veneer.
        Image {
            anchors.fill: parent
            visible: root.grain
            source: Quickshell.shellPath("assets/textures/paper-grain.png")
            fillMode: Image.Tile
            opacity: 0.35
            cache: true
            smooth: true
            asynchronous: true
        }

        // Matte overhead light — bright along the top, a whisper of shade at the foot.
        Rectangle {
            anchors.fill: parent
            visible: root.topLight
            gradient: Gradient {
                GradientStop { position: 0.00; color: Qt.rgba(1, 1, 1, 0.10) }
                GradientStop { position: 0.15; color: "transparent" }
                GradientStop { position: 0.85; color: "transparent" }
                GradientStop { position: 1.00; color: Qt.rgba(0, 0, 0, 0.06) }
            }
        }

        // Left spine gutter — the binding shadow curving in from the bezel, with a thin
        // fold highlight where the page lifts back up out of the crease.
        Item {
            visible: root.spine
            anchors { left: parent.left; top: parent.top; bottom: parent.bottom }
            width: root.spineWidth
            Rectangle {
                anchors.fill: parent
                gradient: Gradient {
                    orientation: Gradient.Horizontal
                    GradientStop { position: 0.00; color: Qt.rgba(0.13, 0.09, 0.06, 0.32) }
                    GradientStop { position: 0.35; color: Qt.rgba(0.13, 0.09, 0.06, 0.10) }
                    GradientStop { position: 1.00; color: "transparent" }
                }
            }
            // Fold sheen — the paper catching light as it rises out of the gutter.
            Rectangle {
                x: parent.width * 0.6
                width: 1
                height: parent.height
                color: root.pageLight
                opacity: 0.4
            }
        }

        // Bottom + right page-edge lift — the outer fore-edges stacked and rising off the
        // desk, curling at the bottom-right corner, over a soft cast shadow.
        Canvas {
            id: liftCanvas
            visible: root.lift
            anchors.fill: parent
            onPaint: {
                const ctx = getContext("2d");
                ctx.clearRect(0, 0, width, height);
                const inset = root.spineWidth * 0.5; // page stack starts just past the gutter
                const layers = 4;
                const gap = 3.2;                     // page thickness
                const bow = 4;                       // gentle curl (a page, not a fat booklet)

                // --- Soft cast shadow: the lit page floating a hair above the desk ---
                // Bottom band
                let bg = ctx.createLinearGradient(0, height - 10, 0, height);
                bg.addColorStop(0.0, Qt.rgba(0, 0, 0, 0.0));
                bg.addColorStop(1.0, Qt.rgba(0, 0, 0, 0.22));
                ctx.fillStyle = bg;
                ctx.fillRect(inset, height - 10, width - inset, 10);
                // Right band
                let rg = ctx.createLinearGradient(width - 10, 0, width, 0);
                rg.addColorStop(0.0, Qt.rgba(0, 0, 0, 0.0));
                rg.addColorStop(1.0, Qt.rgba(0, 0, 0, 0.18));
                ctx.fillStyle = rg;
                ctx.fillRect(width - 10, 6, 10, height - 6);

                // --- Stacked fore-edges: a light lip over a darker crease, per layer ---
                for (let i = layers - 1; i >= 0; i--) {
                    const off = i * gap;
                    // Bottom edge (runs left→right, curling up toward the outer corner)
                    const yb = height - 3 - off;
                    ctx.beginPath();
                    ctx.moveTo(inset, yb + 1.3);
                    ctx.quadraticCurveTo(width * 0.65, yb + 1.3 - bow, width - 3 - off, yb + 1.3);
                    ctx.lineWidth = 1.3; ctx.globalAlpha = 0.7; ctx.strokeStyle = root.pageShadow;
                    ctx.stroke();
                    ctx.beginPath();
                    ctx.moveTo(inset, yb);
                    ctx.quadraticCurveTo(width * 0.65, yb - bow, width - 3 - off, yb);
                    ctx.lineWidth = 1.5; ctx.globalAlpha = 1.0; ctx.strokeStyle = root.pageLight;
                    ctx.stroke();

                    // Right edge (runs top→bottom, curling in toward the outer corner)
                    const xr = width - 3 - off;
                    ctx.beginPath();
                    ctx.moveTo(xr + 1.3, 6);
                    ctx.quadraticCurveTo(xr + 1.3 - bow, height * 0.55, xr + 1.3, height - 3 - off);
                    ctx.lineWidth = 1.3; ctx.globalAlpha = 0.7; ctx.strokeStyle = root.pageShadow;
                    ctx.stroke();
                    ctx.beginPath();
                    ctx.moveTo(xr, 6);
                    ctx.quadraticCurveTo(xr - bow, height * 0.55, xr, height - 3 - off);
                    ctx.lineWidth = 1.5; ctx.globalAlpha = 1.0; ctx.strokeStyle = root.pageLight;
                    ctx.stroke();
                }
                ctx.globalAlpha = 1.0;
            }
            onWidthChanged: requestPaint()
            onHeightChanged: requestPaint()
        }
    }

    // Warm cut-paper edges — only on the three OUTER sides. The LEFT is the bound spine
    // (no cut edge), so it stays borderless and melts into the gutter shadow.
    Rectangle { // top
        anchors { top: parent.top; left: parent.left; right: parent.right }
        height: 1
        color: root.paperEdge
    }
    Rectangle { // right
        anchors { top: parent.top; right: parent.right; bottom: parent.bottom }
        width: 1
        color: root.paperEdge
    }
    Rectangle { // bottom
        anchors { left: parent.left; right: parent.right; bottom: parent.bottom }
        height: 1
        color: root.paperEdge
    }
}
