-- Generated by matugen — do not edit.
-- Updated on each wallpaper change by doorway-matugen-watcher.service.
-- Sourced via pcall(dofile, ...) in dynamic.lua when the file exists.
hl.config({
    general = {
        col = {
            active_border   = "rgba({{colors.primary.default.hex_stripped}}ee)",
            inactive_border = "rgba({{colors.surface_variant.default.hex_stripped}}88)",
        }
    }
})
