pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import qs.modules.common
import qs.modules.common.functions
import qs.services

/**
 * Cartridge-mode switcher — dark (gray NES cart) vs gold (gold LoZ cart).
 * Sets Config appearance.palette.mode, which persists to config.json and drives
 * DoorwayPalette.goldCart → Appearance.m3colors. Replaces the ii-port
 * MaterialThemeLoader, which watched a matugen colors.json DOORway never generates.
 *
 * Auto mode (appearance.palette.autoMode) follows the same sunset/sunrise window
 * as the blue-light filter: gold cart by day, dark cart by night. A manual toggle
 * overrides auto until the next day/night boundary, mirroring Hyprsunset's
 * manualActive semantics.
 *
 * Every mode change also propagates to the freedesktop color-scheme via gsettings,
 * so portal-aware apps (Firefox, GTK, KF6) follow the cartridge.
 *
 * Every mode change also repaints Hyprland's window border colors from the
 * committed DoorwayPalette (gold LED-lit highlight when focused, molded
 * cartridge-edge tone when not) — applied live via hyprctl and persisted to
 * a cache file dynamic.lua dofiles on reload. This replaces matugen's
 * wallpaper-derived border colors as the default; matugen stays available
 * as an opt-in override (doorway.theme.matugenBorders.enable).
 */
Singleton {
    id: root

    readonly property bool goldCart: DoorwayPalette.goldCart
    readonly property string cartridgeColorsPath: FileUtils.trimFileProtocol(`${Directories.genericCache}/doorway/hyprland-cartridge-colors.lua`)
    property bool autoMode: (Config.options?.appearance?.palette?.autoMode ?? true) && (Config?.ready ?? true)
    property bool nightNow: Hyprsunset.shouldBeOn
    // undefined, or set by a manual toggle; cleared at the next day/night boundary
    property var manualOverride

    // Singletons are lazily instantiated, and the IpcHandler/GlobalShortcut below
    // only register once the singleton exists. shell.qml calls this at startup.
    function load() {
        root.applyAuto();
        root.propagate();
    }

    onNightNowChanged: {
        root.manualOverride = undefined;
        root.applyAuto();
    }
    onAutoModeChanged: root.applyAuto()
    // Covers every mode-change path (IPC, launcher, config.json load) in one place.
    onGoldCartChanged: root.propagate()

    function applyAuto() {
        if (!root.autoMode || root.manualOverride !== undefined)
            return;
        root.setMode(root.nightNow ? "dark" : "gold");
    }

    // Mirror the cartridge into the system color-scheme; xdg-desktop-portal-gtk
    // serves org.freedesktop.appearance from dconf, so one write reaches all
    // portal-aware apps. dconf (not gsettings) because the session env lacks
    // compiled glib schemas — gsettings fails with "No schemas installed".
    function propagate() {
        const scheme = root.goldCart ? "prefer-light" : "prefer-dark";
        Quickshell.execDetached(["dconf", "write", "/org/gnome/desktop/interface/color-scheme", `'${scheme}'`]);
        root.writeCartridgeColors();
    }

    // 0.0-1.0 float channel -> two-digit hex, for building rgba(RRGGBBAA) strings.
    function toHex2(v) {
        const byte = Math.max(0, Math.min(255, Math.round(v * 255)));
        return byte.toString(16).padStart(2, "0");
    }

    function hyprlandHex(c, alphaByte) {
        return root.toHex2(c.r) + root.toHex2(c.g) + root.toHex2(c.b) + root.toHex2(alphaByte / 255);
    }

    // Window borders as cartridge hardware: focused = lit gold LED (the same
    // ledGold token bar/dialog "ON" indicators use), unfocused = the molded
    // plastic edge the shell chrome is built from. Full opacity on both keeps
    // them legible against any wallpaper, since they no longer sample one.
    function writeCartridgeColors() {
        const active = root.hyprlandHex(DoorwayPalette.powerGold, 255);
        const inactive = root.hyprlandHex(DoorwayPalette.plasticEdge, 255);
        // dynamic.lua's own mkdir (dofile'd once per Hyprland load) usually wins
        // the race, but this covers writing before that has ever run.
        Quickshell.execDetached(["mkdir", "-p", FileUtils.trimFileProtocol(`${Directories.genericCache}/doorway`)]);
        // Via HyprlandConfig (hyprctl eval), not `hyprctl keyword`: on a lua
        // config Hyprland refuses keyword for every option ("keyword can't work
        // with non-legacy parsers. Use eval."). These two calls silently did
        // nothing, so border colours only ever landed on the next reload, when
        // dynamic.lua dofile'd the cache file written just below. Now they apply
        // live as the comment above always claimed.
        HyprlandConfig.setMany({
            "general:col.active_border": `rgba(${active})`,
            "general:col.inactive_border": `rgba(${inactive})`
        });
        cartridgeColorsFileView.setText(
            "-- Generated by ThemeMode.qml (services/ThemeMode.qml) — do not edit.\n" +
            "-- Cartridge-driven window border colors; dofile'd by dynamic.lua on reload.\n" +
            "hl.config({\n" +
            "    general = {\n" +
            "        col = {\n" +
            `            active_border   = "rgba(${active})",\n` +
            `            inactive_border = "rgba(${inactive})",\n` +
            "        },\n" +
            "    },\n" +
            "})\n"
        );
    }

    function setMode(mode) {
        // Accept the generic light/dark vocabulary used by upstream call sites.
        if (mode === "light") mode = "gold";
        if (mode !== "gold" && mode !== "dark") return;
        Config.options.appearance.palette.mode = mode;
    }

    function toggleLightDark() {
        const mode = root.goldCart ? "dark" : "gold";
        root.manualOverride = mode;
        root.setMode(mode);
    }

    FileView {
        id: cartridgeColorsFileView
        path: Qt.resolvedUrl(root.cartridgeColorsPath)
        printErrors: false
    }

    GlobalShortcut {
        name: "toggleLightDark"
        description: "Toggle between the dark (gray) and gold cartridge schemes"

        onPressed: {
            root.toggleLightDark();
        }
    }

    IpcHandler {
        target: "theme"

        function toggleLightDark(): void {
            root.toggleLightDark();
        }

        function setMode(mode: string): void {
            root.setMode(mode);
        }

        function getMode(): string {
            return Config.options?.appearance?.palette?.mode ?? "unset";
        }
    }
}
